spring.application.name=money_manager

base.api=/api/v1/admin


spring.datasource.url=jdbc:mariadb://185.170.198.166:3306/dbmngr
spring.datasource.username=userdev
spring.datasource.password=password123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

logging.file.name=app.log
logging.level.org.hibernate.SQL=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lordgentro@gmail.com
spring.mail.password=immw lbuc lrtg fwev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mid.merchant.id=G111455079
mid.key=SB-Mid-client-_vgv43K6mZmk0PCm
mid.secret.key=SB-Mid-server-yfbU1bC_wVS8RML2LAQD9gHV
mid.uri.sandbox=https://app.sandbox.midtrans.com/snap/v1/transactions
midtrans.is-production=false

springdoc.swagger-ui.path=/api-docs
springdoc.api-docs.path=/v3/api-documentation

file.upload-dir=src/main/resources/static/uploads/